export const ERROR_CODES = {
  SECRET_EMPTY: 'SECRET_EMPTY',
  SECRET_PARSE_FAILED: 'SECRET_PARSE_FAILED',
  SECRET_SHAPE_INVALID: 'SECRET_SHAPE_INVALID',
  SSM_EMPTY: 'SSM_EMPTY',
  SQS_URL_MISSING: 'SQS_URL_MISSING',
  DB_AUTH_FAILED: 'DB_AUTH_FAILED',
  POISON_MESSAGE: 'POISON_MESSAGE',
  DLQ_FORWARD_FAILED: 'DLQ_FORWARD_FAILED',
  TRANSIENT: 'TRANSIENT',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const DLQ_SOURCE_RELAY = 'pay-callback-relay';
