export const TERMINAL_STATUSES = ['SENT', 'FATAL'] as const;

export const OUTBOX_STATUS = {
  ENQUEUED: 'ENQUEUED',
  SENT: 'SENT',
  FATAL: 'FATAL',
} as const;

export const SALESFORCE_STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;
